"""Aster → Python transpiler.

Compiles an Aster AST to valid Python 3.11+ source code.

Mapping summary
---------------
fn f(x: T) -> R:  →  def f(x):
x := expr          →  x = expr          (type annotations dropped)
mut x := expr      →  x = expr          (mutability tracked by interpreter, not Python)
x <- expr          →  x = expr
true / false       →  True / False
nil                →  None
not / and / or     →  not / and / or
match n: arms      →  if/elif/else chain
use mod            →  import mod
use mod: a, b      →  from mod import a, b
use mod as m       →  import mod as m
print(x)           →  print(x)          (built-in names map directly to Python)
"""

from __future__ import annotations

from dataclasses import dataclass, field

from aster_lang import ast
from aster_lang.parser import parse_module

INDENT = "    "

# Built-in names that map 1-to-1 to Python
_PASSTHROUGH_BUILTINS = frozenset({"print", "len", "str", "int", "abs", "max", "min", "range"})


@dataclass(slots=True)
class CompilationArtifact:
    """Result of compiling an Aster program."""

    stage: str = "python"
    code: str = ""
    errors: list[str] = field(default_factory=list)

    def summary(self) -> str:
        if self.errors:
            return f"Compilation failed: {'; '.join(self.errors)}"
        lines = self.code.count("\n")
        return f"Compiled to Python ({lines} lines)"


class Transpiler:
    """Walk an Aster AST and emit Python source."""

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._depth: int = 0
        self._has_main: bool = False

    # ------------------------------------------------------------------
    # Output helpers

    def _emit(self, text: str) -> None:
        self._lines.append(INDENT * self._depth + text)

    def _blank(self) -> None:
        self._lines.append("")

    # ------------------------------------------------------------------
    # Public entry point

    def transpile(self, module: ast.Module) -> str:
        # Emit runtime shim (bool literals, nil)
        self._emit("# Generated by the Aster compiler")
        self._blank()

        for i, decl in enumerate(module.declarations):
            if i > 0:
                self._blank()
            self._transpile_decl(decl)

        # Emit __main__ guard if main() was defined
        if self._has_main:
            self._blank()
            self._emit('if __name__ == "__main__":')
            self._depth += 1
            self._emit("main()")
            self._depth -= 1

        return "\n".join(self._lines) + "\n"

    # ------------------------------------------------------------------
    # Declarations

    def _transpile_decl(self, decl: ast.Decl) -> None:
        if isinstance(decl, ast.FunctionDecl):
            self._transpile_fn(decl)
        elif isinstance(decl, ast.LetDecl):
            self._emit(f"{decl.name} = {self._expr(decl.initializer)}")
        elif isinstance(decl, ast.ImportDecl):
            self._transpile_import(decl)
        elif isinstance(decl, ast.TypeAliasDecl):
            pass  # Type aliases have no Python runtime representation

    def _transpile_fn(self, decl: ast.FunctionDecl) -> None:
        if decl.name == "main":
            self._has_main = True
        pub = ""  # pub has no Python equivalent
        _ = pub
        params = ", ".join(p.name for p in decl.params)
        self._emit(f"def {decl.name}({params}):")
        self._depth += 1
        if not decl.body:
            self._emit("pass")
        else:
            for stmt in decl.body:
                self._transpile_stmt(stmt)
        self._depth -= 1

    def _transpile_import(self, decl: ast.ImportDecl) -> None:
        module_path = ".".join(decl.module.parts)
        if decl.alias:
            self._emit(f"import {module_path} as {decl.alias}")
        elif decl.imports:
            names = ", ".join(decl.imports)
            self._emit(f"from {module_path} import {names}")
        else:
            self._emit(f"import {module_path}")

    # ------------------------------------------------------------------
    # Statements

    def _transpile_stmt(self, stmt: ast.Stmt) -> None:
        if isinstance(stmt, ast.LetStmt):
            self._emit(f"{stmt.name} = {self._expr(stmt.initializer)}")
        elif isinstance(stmt, ast.AssignStmt):
            self._emit(f"{self._expr(stmt.target)} = {self._expr(stmt.value)}")
        elif isinstance(stmt, ast.ReturnStmt):
            if stmt.value is not None:
                self._emit(f"return {self._expr(stmt.value)}")
            else:
                self._emit("return")
        elif isinstance(stmt, ast.IfStmt):
            self._transpile_if(stmt)
        elif isinstance(stmt, ast.WhileStmt):
            self._emit(f"while {self._expr(stmt.condition)}:")
            self._depth += 1
            for s in stmt.body:
                self._transpile_stmt(s)
            self._depth -= 1
        elif isinstance(stmt, ast.ForStmt):
            self._emit(f"for {stmt.variable} in {self._expr(stmt.iterable)}:")
            self._depth += 1
            for s in stmt.body:
                self._transpile_stmt(s)
            self._depth -= 1
        elif isinstance(stmt, ast.BreakStmt):
            self._emit("break")
        elif isinstance(stmt, ast.ContinueStmt):
            self._emit("continue")
        elif isinstance(stmt, ast.MatchStmt):
            self._transpile_match(stmt)
        elif isinstance(stmt, ast.ExprStmt):
            self._emit(self._expr(stmt.expr))

    def _transpile_if(self, stmt: ast.IfStmt, keyword: str = "if") -> None:
        self._emit(f"{keyword} {self._expr(stmt.condition)}:")
        self._depth += 1
        for s in stmt.then_block:
            self._transpile_stmt(s)
        self._depth -= 1
        if stmt.else_block:
            if len(stmt.else_block) == 1 and isinstance(stmt.else_block[0], ast.IfStmt):
                self._transpile_if(stmt.else_block[0], keyword="elif")
            else:
                self._emit("else:")
                self._depth += 1
                for s in stmt.else_block:
                    self._transpile_stmt(s)
                self._depth -= 1

    def _transpile_match(self, stmt: ast.MatchStmt) -> None:
        """Emit a match statement as an if/elif/else chain."""
        subj = self._expr(stmt.subject)
        first = True
        has_wildcard_or_binding = False

        for arm in stmt.arms:
            pat = arm.pattern
            keyword = "if" if first else "elif"
            first = False

            if isinstance(pat, ast.WildcardPattern | ast.BindingPattern):
                self._emit("else:")
                has_wildcard_or_binding = True
            elif isinstance(pat, ast.LiteralPattern):
                lit_py = self._expr(pat.literal)
                self._emit(f"{keyword} {subj} == {lit_py}:")
            else:
                self._emit(f"{keyword} True:  # unknown pattern")

            self._depth += 1
            # For binding patterns inject the bound variable
            if isinstance(pat, ast.BindingPattern):
                self._emit(f"{pat.name} = {subj}")
            for s in arm.body:
                self._transpile_stmt(s)
            self._depth -= 1

            if has_wildcard_or_binding:
                break  # wildcard/binding arm must be last

        # If there were no wildcard/binding arms, no else needed

    # ------------------------------------------------------------------
    # Expressions

    def _expr(self, expr: ast.Expr) -> str:
        if isinstance(expr, ast.IntegerLiteral):
            return str(expr.value)
        if isinstance(expr, ast.StringLiteral):
            escaped = (
                expr.value.replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\t", "\\t")
            )
            return f'"{escaped}"'
        if isinstance(expr, ast.BoolLiteral):
            return "True" if expr.value else "False"
        if isinstance(expr, ast.NilLiteral):
            return "None"
        if isinstance(expr, ast.Identifier):
            return expr.name
        if isinstance(expr, ast.QualifiedName):
            return ".".join(expr.parts)
        if isinstance(expr, ast.BinaryExpr):
            left = self._expr_paren(expr.left, expr.operator)
            right = self._expr_paren(expr.right, expr.operator)
            op = expr.operator
            return f"{left} {op} {right}"
        if isinstance(expr, ast.UnaryExpr):
            operand = self._expr(expr.operand)
            if expr.operator == "not":
                return f"not {operand}"
            return f"{expr.operator}{operand}"
        if isinstance(expr, ast.CallExpr):
            func = self._expr(expr.func)
            args = ", ".join(self._expr(a) for a in expr.args)
            return f"{func}({args})"
        if isinstance(expr, ast.IndexExpr):
            return f"{self._expr(expr.obj)}[{self._expr(expr.index)}]"
        if isinstance(expr, ast.MemberExpr):
            return f"{self._expr(expr.obj)}.{expr.member}"
        if isinstance(expr, ast.TupleExpr):
            elements = ", ".join(self._expr(e) for e in expr.elements)
            # Single-element tuple needs trailing comma
            if len(expr.elements) == 1:
                return f"({elements},)"
            return f"({elements})"
        if isinstance(expr, ast.ListExpr):
            elements = ", ".join(self._expr(e) for e in expr.elements)
            return f"[{elements}]"
        if isinstance(expr, ast.RecordExpr):
            fields = ", ".join(f'"{f.name}": {self._expr(f.value)}' for f in expr.fields)
            return "{" + fields + "}"
        if isinstance(expr, ast.ParenExpr):
            return f"({self._expr(expr.expr)})"
        return f"None  # unsupported expr: {type(expr).__name__}"

    _PRECEDENCE: dict[str, int] = {
        "or": 1,
        "and": 2,
        "not": 3,
        "==": 4,
        "!=": 4,
        "<": 4,
        ">": 4,
        "<=": 4,
        ">=": 4,
        "+": 5,
        "-": 5,
        "*": 6,
        "/": 6,
        "%": 6,
    }

    def _prec(self, op: str) -> int:
        return self._PRECEDENCE.get(op, 0)

    def _expr_paren(self, expr: ast.Expr, parent_op: str) -> str:
        if isinstance(expr, ast.BinaryExpr) and self._prec(expr.operator) < self._prec(parent_op):
            return f"({self._expr(expr)})"
        return self._expr(expr)


def compile_source(source: str) -> CompilationArtifact:
    """Compile Aster source to Python."""
    try:
        module = parse_module(source)
        code = Transpiler().transpile(module)
        return CompilationArtifact(stage="python", code=code)
    except Exception as e:
        return CompilationArtifact(stage="python", errors=[str(e)])
