"""Aster → Python transpiler.

Compiles an Aster AST to valid Python 3.11+ source code.

Mapping summary
---------------
fn f(x: T) -> R:  →  def f(x):
x := expr          →  x = expr          (type annotations dropped)
mut x := expr      →  x = expr          (mutability tracked by interpreter, not Python)
x <- expr          →  x = expr
true / false       →  True / False
nil                →  None
not / and / or     →  not / and / or
match n: arms      →  if/elif/else chain
use mod            →  import mod
use mod: a, b      →  from mod import a, b
use mod as m       →  import mod as m
print(x)           →  print(x)          (built-in names map directly to Python)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from aster_lang import ast, hir
from aster_lang.module_resolution import ModuleSearchConfig
from aster_lang.parser import parse_module
from aster_lang.semantic import SemanticAnalyzer

INDENT = "    "

# Built-in names that map 1-to-1 to Python
_PASSTHROUGH_BUILTINS = frozenset({"print", "len", "str", "int", "abs", "max", "min", "range"})


@dataclass(slots=True)
class CompilationArtifact:
    """Result of compiling an Aster program."""

    stage: str = "python"
    code: str = ""
    errors: list[str] = field(default_factory=list)

    def summary(self) -> str:
        if self.errors:
            return f"Compilation failed: {'; '.join(self.errors)}"
        lines = self.code.count("\n")
        return f"Compiled to Python ({lines} lines)"


class Transpiler:
    """Walk an Aster AST and emit Python source."""

    def __init__(
        self,
        *,
        module_import_prefix: str | None = None,
        aster_module_labels: frozenset[str] = frozenset(),
    ) -> None:
        self._lines: list[str] = []
        self._depth: int = 0
        self._has_main: bool = False
        self._module_import_prefix = module_import_prefix
        self._aster_module_labels = aster_module_labels
        self._temp_index: int = 0

    # ------------------------------------------------------------------
    # Output helpers

    def _emit(self, text: str) -> None:
        self._lines.append(INDENT * self._depth + text)

    def _blank(self) -> None:
        self._lines.append("")

    def _next_temp(self) -> str:
        name = f"__aster_tmp{self._temp_index}"
        self._temp_index += 1
        return name

    # ------------------------------------------------------------------
    # Public entry point

    def transpile(self, module: ast.Module) -> str:
        # Emit runtime shim (bool literals, nil)
        self._emit("# Generated by the Aster compiler")
        self._blank()

        for i, decl in enumerate(module.declarations):
            if i > 0:
                self._blank()
            self._transpile_decl(decl)

        # Emit __main__ guard if main() was defined
        if self._has_main:
            self._blank()
            self._emit('if __name__ == "__main__":')
            self._depth += 1
            self._emit("main()")
            self._depth -= 1

        return "\n".join(self._lines) + "\n"

    # ------------------------------------------------------------------
    # Declarations

    def _transpile_decl(self, decl: ast.Decl) -> None:
        if isinstance(decl, ast.FunctionDecl):
            self._transpile_fn(decl)
        elif isinstance(decl, ast.LetDecl):
            self._emit(f"{decl.name} = {self._expr(decl.initializer)}")
        elif isinstance(decl, ast.ImportDecl):
            self._transpile_import(decl)
        elif isinstance(decl, ast.TypeAliasDecl):
            pass  # Type aliases have no Python runtime representation

    def _transpile_fn(self, decl: ast.FunctionDecl) -> None:
        if decl.name == "main":
            self._has_main = True
        pub = ""  # pub has no Python equivalent
        _ = pub
        params = ", ".join(p.name for p in decl.params)
        self._emit(f"def {decl.name}({params}):")
        self._depth += 1
        if not decl.body:
            self._emit("pass")
        else:
            for stmt in decl.body:
                self._transpile_stmt(stmt)
        self._depth -= 1

    def _transpile_import(self, decl: ast.ImportDecl) -> None:
        module_path = ".".join(decl.module.parts)
        is_aster_module = module_path in self._aster_module_labels
        full_path = module_path
        if self._module_import_prefix and is_aster_module:
            full_path = f"{self._module_import_prefix}.{module_path}"
        if decl.alias:
            self._emit(f"import {full_path} as {decl.alias}")
            return
        if decl.imports:
            names = ", ".join(decl.imports)
            self._emit(f"from {full_path} import {names}")
            return

        # Namespace import: bind the module namespace to the last name by default.
        binding_name = decl.module.parts[-1]
        if "." in module_path or (self._module_import_prefix and is_aster_module):
            self._emit(f"import {full_path} as {binding_name}")
        else:
            self._emit(f"import {full_path}")

    # ------------------------------------------------------------------
    # Statements

    def _transpile_stmt(self, stmt: ast.Stmt) -> None:
        if isinstance(stmt, ast.LetStmt):
            if self._pattern_contains_record(stmt.pattern):
                temp = self._next_temp()
                self._emit(f"{temp} = {self._expr(stmt.initializer)}")
                cond = self._pattern_cond(stmt.pattern, temp)
                if cond != "True":
                    self._emit(f"if not ({cond}):")
                    self._depth += 1
                    self._emit('raise RuntimeError("Binding pattern does not match initializer")')
                    self._depth -= 1
                self._pattern_emit_bindings(stmt.pattern, temp)
            else:
                self._emit(f"{self._binding_target(stmt.pattern)} = {self._expr(stmt.initializer)}")
        elif isinstance(stmt, ast.AssignStmt):
            self._emit(f"{self._expr(stmt.target)} = {self._expr(stmt.value)}")
        elif isinstance(stmt, ast.ReturnStmt):
            if stmt.value is not None:
                self._emit(f"return {self._expr(stmt.value)}")
            else:
                self._emit("return")
        elif isinstance(stmt, ast.IfStmt):
            self._transpile_if(stmt)
        elif isinstance(stmt, ast.WhileStmt):
            self._emit(f"while {self._expr(stmt.condition)}:")
            self._depth += 1
            for s in stmt.body:
                self._transpile_stmt(s)
            self._depth -= 1
        elif isinstance(stmt, ast.ForStmt):
            self._emit(f"for {stmt.variable} in {self._expr(stmt.iterable)}:")
            self._depth += 1
            for s in stmt.body:
                self._transpile_stmt(s)
            self._depth -= 1
        elif isinstance(stmt, ast.BreakStmt):
            self._emit("break")
        elif isinstance(stmt, ast.ContinueStmt):
            self._emit("continue")
        elif isinstance(stmt, ast.MatchStmt):
            self._transpile_match(stmt)
        elif isinstance(stmt, ast.ExprStmt):
            self._emit(self._expr(stmt.expr))

    def _transpile_if(self, stmt: ast.IfStmt, keyword: str = "if") -> None:
        self._emit(f"{keyword} {self._expr(stmt.condition)}:")
        self._depth += 1
        for s in stmt.then_block:
            self._transpile_stmt(s)
        self._depth -= 1
        if stmt.else_block:
            if len(stmt.else_block) == 1 and isinstance(stmt.else_block[0], ast.IfStmt):
                self._transpile_if(stmt.else_block[0], keyword="elif")
            else:
                self._emit("else:")
                self._depth += 1
                for s in stmt.else_block:
                    self._transpile_stmt(s)
                self._depth -= 1

    def _transpile_match(self, stmt: ast.MatchStmt) -> None:
        """Emit a match statement as an if/elif/else chain."""
        subj = self._expr(stmt.subject)
        first = True
        has_wildcard_or_binding = False

        for arm in stmt.arms:
            pat = arm.pattern
            keyword = "if" if first else "elif"
            first = False

            if isinstance(pat, ast.WildcardPattern | ast.BindingPattern):
                self._emit("else:")
                has_wildcard_or_binding = True
            elif isinstance(pat, ast.LiteralPattern):
                lit_py = self._expr(pat.literal)
                self._emit(f"{keyword} {subj} == {lit_py}:")
            elif isinstance(pat, ast.OrPattern):
                if self._or_pattern_is_irrefutable(pat):
                    self._emit("else:")
                    has_wildcard_or_binding = True
                else:
                    cond = self._pattern_cond(pat, subj)
                    self._emit(f"{keyword} {cond}:")
            elif isinstance(pat, ast.ListPattern | ast.TuplePattern | ast.RecordPattern):
                cond = self._pattern_cond(pat, subj)
                self._emit(f"{keyword} {cond}:")
            else:
                self._emit(f"{keyword} True:  # unknown pattern")

            self._depth += 1
            if isinstance(pat, ast.BindingPattern):
                self._emit(f"{pat.name} = {subj}")
            elif isinstance(
                pat, ast.OrPattern | ast.ListPattern | ast.TuplePattern | ast.RecordPattern
            ):
                self._pattern_emit_bindings(pat, subj)
            for s in arm.body:
                self._transpile_stmt(s)
            self._depth -= 1

            if has_wildcard_or_binding:
                break  # wildcard/binding arm must be last

        # If there were no wildcard/binding arms, no else needed

    def _or_pattern_is_irrefutable(self, pat: ast.OrPattern) -> bool:
        """Return True if at least one alternative always matches (binding or wildcard)."""
        return any(
            isinstance(alt, ast.BindingPattern | ast.WildcardPattern) for alt in pat.alternatives
        )

    def _pattern_cond(self, pattern: ast.Pattern, subj: str) -> str:
        """Return a Python boolean expression for matching subj against pattern."""
        if isinstance(pattern, ast.WildcardPattern | ast.BindingPattern | ast.RestPattern):
            return "True"
        if isinstance(pattern, ast.LiteralPattern):
            return f"{subj} == {self._expr(pattern.literal)}"
        if isinstance(pattern, ast.ListPattern):
            return self._sequence_pattern_cond(pattern.elements, subj, "list")
        if isinstance(pattern, ast.TuplePattern):
            return self._sequence_pattern_cond(pattern.elements, subj, "tuple")
        if isinstance(pattern, ast.RecordPattern):
            return self._record_pattern_cond(pattern, subj)
        if isinstance(pattern, ast.OrPattern):
            parts = [f"({self._pattern_cond(alt, subj)})" for alt in pattern.alternatives]
            return " or ".join(parts)
        return "True"  # unhandled pattern kind

    def _sequence_pattern_cond(self, elements: list[ast.Pattern], subj: str, kind: str) -> str:
        """Condition for a list or tuple pattern against subj."""
        has_rest = any(isinstance(e, ast.RestPattern) for e in elements)
        non_rest = [e for e in elements if not isinstance(e, ast.RestPattern)]
        n = len(non_rest)

        parts: list[str] = [f"isinstance({subj}, {kind})"]
        if has_rest:
            if n > 0:
                parts.append(f"len({subj}) >= {n}")
        else:
            parts.append(f"len({subj}) == {n}")

        for i, elem in enumerate(elements):
            if isinstance(elem, ast.RestPattern):
                continue
            cond = self._pattern_cond(elem, f"{subj}[{i}]")
            if cond != "True":
                parts.append(cond)

        return " and ".join(parts)

    def _record_pattern_cond(self, pattern: ast.RecordPattern, subj: str) -> str:
        """Condition for a record pattern against subj."""
        parts: list[str] = [f"isinstance({subj}, dict)"]
        for f in pattern.fields:
            parts.append(f'"{f.name}" in {subj}')
            cond = self._pattern_cond(f.pattern, f'{subj}["{f.name}"]')
            if cond != "True":
                parts.append(cond)
        return " and ".join(parts)

    def _pattern_emit_bindings(self, pattern: ast.Pattern, subj: str) -> None:
        """Emit Python assignment statements for all bindings introduced by pattern."""
        if isinstance(pattern, ast.BindingPattern | ast.RestPattern):
            self._emit(f"{pattern.name} = {subj}")
        elif isinstance(pattern, ast.ListPattern | ast.TuplePattern):
            for i, elem in enumerate(pattern.elements):
                if isinstance(elem, ast.RestPattern):
                    self._pattern_emit_bindings(elem, f"{subj}[{i}:]")
                else:
                    self._pattern_emit_bindings(elem, f"{subj}[{i}]")
        elif isinstance(pattern, ast.RecordPattern):
            for field in pattern.fields:
                self._pattern_emit_bindings(field.pattern, f'{subj}["{field.name}"]')
        elif isinstance(pattern, ast.OrPattern):
            # Skip entirely when no alternative introduces a binding.
            if not any(self._pattern_has_bindings(alt) for alt in pattern.alternatives):
                return
            if self._or_pattern_is_irrefutable(pattern):
                for alt in pattern.alternatives:
                    if isinstance(alt, ast.BindingPattern):
                        self._emit(f"{alt.name} = {subj}")
                        return
            else:
                # Refutable: emit nested if/else to pick the matching alternative
                first = True
                for alt in pattern.alternatives:
                    cond = self._pattern_cond(alt, subj)
                    kw = "if" if first else "elif"
                    first = False
                    self._emit(f"{kw} {cond}:")
                    self._depth += 1
                    self._pattern_emit_bindings(alt, subj)
                    self._depth -= 1
        # WildcardPattern, LiteralPattern: no bindings

    def _pattern_has_bindings(self, pattern: ast.Pattern) -> bool:
        """Return True if pattern introduces any variable binding."""
        if isinstance(pattern, ast.BindingPattern | ast.RestPattern):
            return True
        if isinstance(pattern, ast.OrPattern):
            return any(self._pattern_has_bindings(alt) for alt in pattern.alternatives)
        if isinstance(pattern, ast.ListPattern | ast.TuplePattern):
            return any(self._pattern_has_bindings(e) for e in pattern.elements)
        if isinstance(pattern, ast.RecordPattern):
            return any(self._pattern_has_bindings(f.pattern) for f in pattern.fields)
        return False

    def _pattern_contains_record(self, pattern: ast.Pattern) -> bool:
        """Return True if pattern contains a record pattern anywhere."""
        if isinstance(pattern, ast.RecordPattern):
            return True
        if isinstance(pattern, ast.OrPattern):
            return any(self._pattern_contains_record(alt) for alt in pattern.alternatives)
        if isinstance(pattern, ast.ListPattern | ast.TuplePattern):
            return any(self._pattern_contains_record(elem) for elem in pattern.elements)
        return False

    def _binding_target(self, pattern: ast.Pattern) -> str:
        """Translate a local binding pattern to a Python assignment target."""
        if isinstance(pattern, ast.BindingPattern):
            return pattern.name
        if isinstance(pattern, ast.WildcardPattern):
            return "_"
        if isinstance(pattern, ast.RestPattern):
            return f"*{pattern.name}"
        if isinstance(pattern, ast.TuplePattern):
            inner = ", ".join(self._binding_target(element) for element in pattern.elements)
            if len(pattern.elements) == 1:
                inner += ","
            return f"({inner})"
        if isinstance(pattern, ast.ListPattern):
            inner = ", ".join(self._binding_target(element) for element in pattern.elements)
            return f"[{inner}]"
        raise ValueError(
            f"Compiler does not support destructuring binding pattern " f"{type(pattern).__name__}"
        )

    # ------------------------------------------------------------------
    # Expressions

    def _expr(self, expr: ast.Expr) -> str:
        if isinstance(expr, ast.IntegerLiteral):
            return str(expr.value)
        if isinstance(expr, ast.StringLiteral):
            escaped = (
                expr.value.replace("\\", "\\\\")
                .replace('"', '\\"')
                .replace("\n", "\\n")
                .replace("\t", "\\t")
            )
            return f'"{escaped}"'
        if isinstance(expr, ast.BoolLiteral):
            return "True" if expr.value else "False"
        if isinstance(expr, ast.NilLiteral):
            return "None"
        if isinstance(expr, ast.Identifier):
            return expr.name
        if isinstance(expr, ast.QualifiedName):
            return ".".join(expr.parts)
        if isinstance(expr, ast.BinaryExpr):
            left = self._expr_paren(expr.left, expr.operator)
            right = self._expr_paren(expr.right, expr.operator)
            op = expr.operator
            return f"{left} {op} {right}"
        if isinstance(expr, ast.UnaryExpr):
            operand = self._expr(expr.operand)
            if expr.operator == "not":
                return f"not {operand}"
            return f"{expr.operator}{operand}"
        if isinstance(expr, ast.CallExpr):
            func = self._expr(expr.func)
            args = ", ".join(self._expr(a) for a in expr.args)
            return f"{func}({args})"
        if isinstance(expr, ast.IndexExpr):
            return f"{self._expr(expr.obj)}[{self._expr(expr.index)}]"
        if isinstance(expr, ast.MemberExpr):
            return f"{self._expr(expr.obj)}.{expr.member}"
        if isinstance(expr, ast.TupleExpr):
            elements = ", ".join(self._expr(e) for e in expr.elements)
            # Single-element tuple needs trailing comma
            if len(expr.elements) == 1:
                return f"({elements},)"
            return f"({elements})"
        if isinstance(expr, ast.ListExpr):
            elements = ", ".join(self._expr(e) for e in expr.elements)
            return f"[{elements}]"
        if isinstance(expr, ast.RecordExpr):
            fields = ", ".join(f'"{f.name}": {self._expr(f.value)}' for f in expr.fields)
            return "{" + fields + "}"
        if isinstance(expr, ast.ParenExpr):
            return f"({self._expr(expr.expr)})"
        return f"None  # unsupported expr: {type(expr).__name__}"

    _PRECEDENCE: dict[str, int] = {
        "or": 1,
        "and": 2,
        "|": 3,
        "^": 4,
        "&": 5,
        "not": 3,
        "==": 6,
        "!=": 6,
        "<": 6,
        ">": 6,
        "<=": 6,
        ">=": 6,
        "<<": 7,
        ">>": 7,
        "+": 8,
        "-": 8,
        "*": 9,
        "/": 9,
        "%": 9,
    }

    def _prec(self, op: str) -> int:
        return self._PRECEDENCE.get(op, 0)

    def _expr_paren(self, expr: ast.Expr, parent_op: str) -> str:
        if isinstance(expr, ast.BinaryExpr) and self._prec(expr.operator) < self._prec(parent_op):
            return f"({self._expr(expr)})"
        return self._expr(expr)


def compile_source(source: str) -> CompilationArtifact:
    """Compile Aster source to Python."""
    try:
        module = parse_module(source)
        code = Transpiler().transpile(module)
        return CompilationArtifact(stage="python", code=code)
    except Exception as e:
        return CompilationArtifact(stage="python", errors=[str(e)])


@dataclass(slots=True)
class HIRBuildResult:
    module: hir.HModule
    errors: list[str] = field(default_factory=list)


def build_hir(
    *,
    entry_path: Path,
    dep_overrides: dict[str, Path] | None = None,
    extra_roots: tuple[Path, ...] = (),
    resolver_config: ModuleSearchConfig | None = None,
) -> HIRBuildResult:
    """Build an entry module into HIR."""
    source = entry_path.read_text(encoding="utf-8")
    module_ast = parse_module(source)
    analyzer = SemanticAnalyzer(
        base_dir=entry_path.parent,
        dep_overrides=dep_overrides,
        extra_roots=extra_roots,
        resolver_config=resolver_config,
    )
    analyzer.analyze(module_ast)
    if analyzer.has_errors():
        return HIRBuildResult(
            module=hir.HModule(decls=()),
            errors=[e.message for e in analyzer.errors],
        )
    return HIRBuildResult(module=hir.lower_module(module_ast, analyzer))
